version: '3'
services:
  leader:
    image: rabbitmq:3.7.14-management
    environment:
      RABBITMQ_NODENAME: rabbitmq1
      RABBITMQ_ERLANG_COOKIE: YZSDHWMFSMKEMBDHSGGZ
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    hostname: leader
  follwer-1:
    image: rabbitmq:3.7.14-management
    environment:
      RABBITMQ_NODENAME: rabbitmq2
      RABBITMQ_ERLANG_COOKIE: YZSDHWMFSMKEMBDHSGGZ
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
    hostname: follwer-1
  follwer-2:
    image: rabbitmq:3.7.14-management
    environment:
      RABBITMQ_NODENAME: rabbitmq3
      RABBITMQ_ERLANG_COOKIE: YZSDHWMFSMKEMBDHSGGZ
    ports:
      - "5674:5672"
      - "15674:15672"
    restart: always
    hostname: follwer-2
networks:
  default:

